### ISSUE TITLE
[Regression] 580.105.08: DisplayPort monitor limited to 1920x1080 instead of native 2560x1440

### ISSUE THREAD

**Issue by darklenre** [NVIDIA/open-gpu-kernel-modules#960]
### NVIDIA Open GPU Kernel Modules Version

580.105.08

### Please confirm this issue does not happen with the proprietary driver (of the same version). This issue tracker is only for bugs specific to the open kernel driver.

- [ ] I confirm that this does not happen with the proprietary driver package.

### Operating System and Version

CachyOS

### Kernel Release

6.17.7-3-cachyos

### Please confirm you are running a stable release kernel (e.g. not a -rc). We do not accept bug reports for unreleased kernels.

- [x] I am running on a stable kernel release.

### Hardware: GPU

NVIDIA RTX A2000 12GB

## Bug Report

**NVIDIA Driver Version:** 580.105.08
**Previous Working Version:** 580.95.05
**GPU:** NVIDIA RTX A2000 12GB
**OS:** CachyOS (Arch-based)
**Kernel:** 6.17.7
**Display Server:** Wayland (KDE Plasma 6.5.1)
**Monitor:** Lenovo ThinkVision T27h-30 (2560x1440 native)
**Connection:** Mini-DisplayPort to DisplayPort

## Issue
After updating from driver 580.95.05 to 580.105.08, my DisplayPort-connected monitor is limited to 1920x1080 maximum resolution instead of its native 2560x1440@60Hz.

## Evidence
- EDID correctly reports 2560x1440 as preferred mode
- `/sys/class/drm/card1-DP-1/modes` shows maximum 1920x1080
- `edid-decode` confirms monitor advertises 2560x1440@60Hz
- Downgrading to 580.95.05 resolves the issue

## Reproduction
1. Update nvidia-utils to 580.105.08
2. Connect 2560x1440 DisplayPort monitor
3. Check available resolutions - maximum is 1920x1080

## Related Reports
Multiple users affected: https://discuss.cachyos.org/t/after-updating-linux-cachyos-nvidia-linux-cachyos-rc-nvidia-linux-cachyos-lts-nvidia-nvidia-driver-version-580-105-08-the-dual-screen-display-resolution-is-incorrect/18057

https://discuss.cachyos.org/t/suddenly-missing-higher-resolution-on-second-monitor/18101/14

### To Reproduce

1. Update nvidia-utils to 580.105.08
2. Connect 2560x1440 DisplayPort monitor
3. Check available resolutions - maximum is 1920x1080

### Bug Incidence

Always

### nvidia-bug-report.log.gz

[nvidia-bug-report.log.gz](https://github.com/user-attachments/files/23383730/nvidia-bug-report.log.gz)

**Comment by CapnArrys** [comment]
I'm also experiencing this same issue, 2560x1080@75Hz limited to 1920x1080@60Hz on HDMI after this update, GPU : NVIDIA RTX 4070

**Comment by Lecer69** [comment]
I also can confirm this issue, after I uninstalled nvidia drivers, to let integraded amd graphics to work, it completely detected the monitor, the modes, the id, the model and etc, but after installing them again, its unable to detect the monitor, and the monitor model id changes to nvidia 0x0000, which is wrong, and it will be locked on 640x480@60Hz resolution.

GPU: RTX 3050

hyprctl monitors:
with nvidia drivers:

Monitor DP-1 (ID 1):
    640x480@59.94000 at 440x993
    description: Nvidia 0x0000
    make: Nvidia
    model: 0x0000
    physical size (mm): 0x0
    serial: 
    active workspace: 4 (4)
    special workspace: 0 ()
    reserved: 0 45 0 0
    scale: 1.00
    transform: 0
    focused: no
    dpmsStatus: 1
    vrr: false
    solitary: 0
    solitaryBlockedBy: windowed mode,missing candidate
    activelyTearing: false
    tearingBlockedBy: next frame is not torn,missing candidate
    directScanoutTo: 0
    directScanoutBlockedBy: user settings,missing candidate
    disabled: false
    currentFormat: XRGB8888
    mirrorOf: none
    availableModes: 640x480@59.94Hz

without nvidia drivers (forcing to use integraded AMD graphics):

Monitor DP-1 (ID 1):
	1920x1080@60.00000 at 0x0
	description: Hewlett Packard HP LA2206 3CQ151BFDD
	make: Hewlett Packard
	model: HP LA2206
	physical size (mm): 480x270
	serial: 3CQ151BFDD
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 45 0 0
	scale: 1.00
	transform: 3
	focused: no
	dpmsStatus: 1
	vrr: false
	solitary: 0
	solitaryBlockedBy: windowed mode,missing candidate
	activelyTearing: false
	tearingBlockedBy: next frame is not torn,missing candidate
	directScanoutTo: 0
	directScanoutBlockedBy: user settings,software renders/cursors,missing candidate
	disabled: false
	currentFormat: XRGB8888
	mirrorOf: none
	availableModes: 1920x1080@60.00Hz 1680x1050@59.95Hz 1280x1024@60.02Hz 1440x900@59.89Hz 1280x800@60.00Hz 1280x720@60.00Hz 1024x768@60.00Hz 800x600@60.32Hz 640x480@59.94Hz 720x400@70.08Hz

**Comment by tpaananen** [comment]
Secondary monitor on HDMI limited to 1980x1080@60 when installed 580.105.08 driver on CachyOS 6.17.7-3, KDE Plasma 6.5.2. Reverting to previous version 580.95.05 resolved the issue for me and now the display is back at 2560x1440@60.

HW: Nvidia RTX 5080

**Comment by Binary-Eater** [comment]
Hi folks, thanks for reporting this regression. Apologies about the impact seen. Will try to get a repro internally to debug this. Will also look at providing possible test patches in case an internal reproduction is non-trivial for some reason.

**Comment by MKlown** [comment]
I can confirm the issue on Arch with a RTX3080Ti if it helps. Reverting drivers to previous version also solve the issue.

**Comment by RainOrigami** [comment]
I have this issue on Endeavour OS with an RTX 4090 using nvidia-dkms, Monitor HDMI-A-2 (ID 0) only supporting up to 1920x1080 while my other two monitors Monitor DP-2 (ID 1) and Monitor DP-3 (ID 2) correctly function in 2560x1440. Reverting to 580.95.05-1 has resolved the issue.

You can tell at boot (nvidia-drm.modeset=1) where the boot process log only shows up on 3/4 of the screen on DP-2 and DP-3 because it is limited by the resolution of HDMI-A-2.

**Comment by care** [comment]
Same issue with 580.95.05 upgrade to 580.105.08 on Arch, using a 1060. Interestingly, the wallpaper on this machine was never set and the default was black (probably set by nvidia conf?), but now after the upgrade it is white. Monitors are the exact same, and only one is capped to 60hz.

**Comment by Centopus** [comment]
I just installed this last night and had to go back to 580.95.05. Because I boot to black screen with cursor blinking. Does not even get the GDM. 

nvidia-drm.modeset=0 lets me boot in low resolution to make a downgrade.

Haven't  got the knowledge to probe what is happening. But I'm able to boot in low resolution to make downgrade.
Got Arch, 4070Ti and 1 DisplayPort 4k Monitor and another HDMI 4k one. Aligns with what has been said before.

PS. If you require more information from me, please give detailed instructions and I shall provide.

**Comment by OtonashiHorobu** [comment]
Same issue here with 580.105.08 RTX 4060 on Arch Linux, where 2560x1440@75Hz is capped to 1920x1080@60Hz.

Using the closed source driver still reproduces the issue.

**Comment by abhilashdwarakanath-dot** [comment]
I can confirm this issue on Manjaro. I was under the impression that Manjaro provided both the proprietary and the -open versions, and I explicitly installed the version without the -open tag, and yet I am facing the same issue. My driver version shows 580.105.08

**Comment by nicolas-s** [comment]
Same issue for me with `580.105.08` and `RTX 5070 Ti` on Arch Linux.
The previous `2560x1440@60Hz` is now limited to `2048x1080@60Hz`.

**Comment by mtijanic** [comment]
Tracked as nvbug 5651624. Also, #959 is a possible duplicate.

**Comment by Woosah** [comment]
Same here with 580.105.08 and GeForce GTX 1060 on Arch Linux.
Previously on 580.95.05: 2560x1440@60Hz
Now limited to 2048x1080@60Hz.

**Comment by es20490446e** [comment]
In my case what is limited is the frame-rate.

**Comment by ricardobarantini** [comment]
Same problem. Driver 580.105.08-1 and GeForce RTX 3060 Ti on Arch. My ultrawide monitor is being recognized at 1920x1080.

**Comment by arunavdey** [comment]
Facing the same issue. Monitor supports 1920x1080@144, but got limited to 1920x1080@60 after upgrading to 580.105.0.   Downgrading to 580.95.05 fixed the issue.

GPU: GTX 1060 6GB
OS: Arch Linux, running swaywm

**Comment by pinnacle-op** [comment]
Dame issue with this drivers on cachyos 6.17.7.3 with rtx 4060 monitor connected via HDMI capped at 1920x1080@60hz reverting to previous version drivers solves the problem.

**Comment by m-obeid** [comment]
Using nvidia-open kernel module, Monitor is LG ULTRAWIDE connected over HDMI (should be 2560x1080@75Hz) capped at 1920x1080@60Hz

Can confirm downgrading to 580.95.05 resolves the issue.

GPU: RTX 3060 12GB
OS: Arch Linux, GNOME 49.1

**Comment by Binary-Eater** [comment]
Just wanted to provide an update that we have a fix internally authored that we are currently verifying.

**Comment by wqshmzh** [comment]
Can CONFIRM this issue. My second 2K monitor connected via HDMI is always limited in 1920x1080@60Hz mode without any chance to set to 2K@75Hz after installing 580.105.08 driver. The old 580.95.05 driver works fine. Please provide a hotfix for 580.105.08 driver as soon as possible to solve this. Much appreciate.

**Comment by HolyBull** [comment]
Can confirm this issue on RTX5070 - after update to 580.105.08 display dropped from 2560x1440@75Hz to 1920x1080@60Hz. Had to downgrade to previous version.

**Comment by es20490446e** [comment]
No need to confirm further.

**Comment by Binary-Eater** [comment]
Hi folks,

I have two sets of orthogonal patches for resolving this issue.

Variant 1 (preferred) - https://github.com/Binary-Eater/open-gpu-kernel-modules/commit/9af5a7d9313f49661c6918cd2954f618bf95dfd9
Patch file - https://github.com/Binary-Eater/open-gpu-kernel-modules/commit/9af5a7d9313f49661c6918cd2954f618bf95dfd9.patch
Variant 2 - https://github.com/Binary-Eater/open-gpu-kernel-modules/commit/14d93b52ce538ba0446508473482fc4da91be3a2
Patch file - https://github.com/Binary-Eater/open-gpu-kernel-modules/commit/14d93b52ce538ba0446508473482fc4da91be3a2.patch

Variant 1 is what we are hoping to ship in a future driver release, but variant 2 is provided in case there is some unique monitor issue with variant 1 for those that would like to test the fix ahead of time.

Thanks,
Rahul Rameshbabu

**Comment by Binary-Eater** [comment]
Hi folks, Actually, we would prefer if variant 2 is widely tested. We are leaning more towards that patch right now for a wider range of monitor fixes.

**Comment by veypatch** [comment]
I just tested this as the patch had been applied to the [linux-cachyos-nvidia-open](https://github.com/CachyOS/linux-cachyos/commit/e200bee2dff183ef3a4cb109d10e4d44dba2b2ea) package. Sadly my LG ULTRAWIDE connected over HDMI (should be 2560x1080@75Hz) is still capped at 1920x1080@60Hz. My second displayport monitor won't output any thing at all (connected through a thinkpad dock). Similar behavior as before this patch.

**Comment by pinnacle-op** [comment]
Even after the patch the problem is not resolved resolution still capped at 60hz.

**Comment by es20490446e** [comment]
[Patch 2](https://github.com/Binary-Eater/open-gpu-kernel-modules/commit/14d93b52ce538ba0446508473482fc4da91be3a2.patch) works well on my [system](https://pastebin.com/raw/8JtixMxG).

Share your **system info** with: `curl --silent https://raw.githubusercontent.com/Askannz/optimus-manager/refs/heads/master/system-info.sh | bash &> ~/system-info.txt`.

If on an Arch Linux derivative, **test the patch** with this [package](https://www.transfernow.net/dl/202511139X2jvB0T). Generated from this [PKGBUILD](https://pastebin.com/raw/cvWr9feV).

**Comment by Binary-Eater** [comment]
> I just tested this as the patch had been applied to the [linux-cachyos-nvidia-open](https://github.com/CachyOS/linux-cachyos/commit/e200bee2dff183ef3a4cb109d10e4d44dba2b2ea) package. Sadly my LG ULTRAWIDE connected over HDMI (should be 2560x1080@75Hz) is still capped at 1920x1080@60Hz. My second displayport monitor won't output any thing at all (connected through a thinkpad dock). Similar behavior as before this patch.

Can you share a dump from nvidia-bug-report.sh or your monitor EDID?

**Comment by Binary-Eater** [comment]
I might be wrong but doesn't the cachyos packaging skip all the NVIDIA patches?

https://github.com/CachyOS/linux-cachyos/blob/e200bee2dff183ef3a4cb109d10e4d44dba2b2ea/linux-cachyos/PKGBUILD#L286-L296

**Comment by Binary-Eater** [comment]
Ah, I see. Let me test this out locally but the EDID capture or nvidia-bug-report.sh dump would be helpful for those still experiencing an issue.

https://github.com/CachyOS/linux-cachyos/blob/e200bee2dff183ef3a4cb109d10e4d44dba2b2ea/linux-cachyos/PKGBUILD#L239-L244

**Comment by Binary-Eater** [comment]
Hmm, interesting. I am running CachyOS with the latest linux-cachy-nvidia-open package and the variant 2 patch does not seem to be applied. If I manually apply the patch, I see the modes that previously were regressed with 580.105.08 with the monitor I am testing with.

```
sudo pacman -Qs linux-cachyos-nvidia-open
[sudo] password for binary-eater:
local/linux-cachyos-nvidia-open 6.17.7-4
    nvidia open modules of 580.105.08 driver for the linux-cachyos kernel
```

**Comment by ptr1337** [comment]
> Hmm, interesting. I am running CachyOS with the latest linux-cachy-nvidia-open package and the variant 2 patch does not seem to be applied. If I manually apply the patch, I see the modes that previously were regressed with 580.105.08 with the monitor I am testing with.
> 
> ```
> sudo pacman -Qs linux-cachyos-nvidia-open
> [sudo] password for binary-eater:
> local/linux-cachyos-nvidia-open 6.17.7-4
>     nvidia open modules of 580.105.08 driver for the linux-cachyos kernel
> ```

Yes, you are right - the patch has not been applied to the direct module, since it got only added in the source array, but not in the prepare patching process.
I have started now a new compilation, which should be available in around 1 hour.

nvidia-open-dkms is fine.

**Comment by Binary-Eater** [comment]
No worries! Thanks for confirming @ptr1337.

**Comment by SupImCinnamon** [comment]
Thank you for the quick fix NVIDIA team!

**Comment by lemminggw** [comment]
I am on latest for cachyos which sounds like it should have the update but my refresh rate has not returned. I use a custom edid to bring 60hz back for 4k that for this dummy plug doesn't show on linux.

I am still a bit new to linux in general but let me know what I could provide or try to help diagnose this. (just might need a bit more help in finding/trying things ;D haha)

**Comment by MKlown** [comment]
Tested Arch with version 580.105.08-2, same issue.
I precise I use HDMI.
hyprctl monitors
Monitor HDMI-A-2 (ID 0):
	3440x1440@49.98700 at 0x0
	description: Sony Acer X34 P T3MSG0044202
	make: Sony
	model: Acer X34 P

Reverting to previous drivers was not enough anymore. I had to downgrade the kernel, previous drivers were not loaded with the new kernel.

Let me know if anything else can help.

**Comment by gcd0318** [comment]
same issue

**Comment by Binary-Eater** [comment]
I don't think vanilla Arch Linux has the patch being discussed?

**Comment by Binary-Eater** [comment]
In general for anyone having issues, sharing dumps from nvidia-bug-report.sh can help us out a lot with understanding the modes being discussed. We are also just thinking about reverting the change in question that caused this regression. However, either way, we can definitely use the nvidia-bug-report dumps to understand the monitors better.

**Comment by lemminggw** [comment]
[nvidia-bug-report.log.gz](https://github.com/user-attachments/files/23537748/nvidia-bug-report.log.gz)
here is mine. hopefully this is correct.

**Comment by Binary-Eater** [comment]
@lemminggw , thank you so much for that bug report. It was extremely helpful. From looking at your EDID, I was able to a) understand why the patch shared did not help your case and b) come up with some judgement calls.

1. I think we are going to revert the change that caused this issue to surface
2. If every user still impacted by this issue can share nvidia-bug-report.sh dumps, that will help us have a larger database as we RCCA this issue and avoid similar regressions as we tackle the problems we hoped to originally solve with the change in question.

**Comment by MKlown** [comment]
[nvidia-bug-report.log.gz](https://github.com/user-attachments/files/23538965/nvidia-bug-report.log.gz)

Here you go. Using last working version.

For the patch, I am not sure. It started with a version -1. Yesterday a version -2 was released and I was hoping...

**Comment by Binary-Eater** [comment]
Thanks @MKlown, reading your EDID, I would have expected the variant 2 patch to have resolved the issue with your monitor specifically. However, @lemminggw's monitor does show some characteristics that the same patch would not resolve.

Looking at Arch Linux's nvidia-open package, I suspect they did not pull in this patch.

https://gitlab.archlinux.org/archlinux/packaging/packages/nvidia-open/-/blob/580.105.08-2/PKGBUILD?ref_type=tags

**Comment by tcoopman** [comment]
Same issue for me, also with `nvidia-open-dkms`.

[nvidia-bug-report.log.gz](https://github.com/user-attachments/files/23542526/nvidia-bug-report.log.gz)

**Comment by Centopus** [comment]
For me the repository version release -2 resolved the issue. 
Sorry. I do not trust myself to try out the patches that your need to self apply. My knowhow is lacking.

Hope the feedback helps a bit.
Arch, 4070Ti, double 4k monitors, one on DP, one on HDMI.

**Comment by EricDriussi** [comment]
Just chiming in to leave my own [nvidia-bug-report.log.gz](https://github.com/user-attachments/files/23544615/nvidia-bug-report.log.gz), since I'm also seeing this issue on an arch derivative distro.
Hope it helps!

**Comment by ptr1337** [comment]
> Hi folks,
> 
> I have two sets of orthogonal patches for resolving this issue.
> 
> Variant 1 (preferred) - [Binary-Eater@9af5a7d](https://github.com/Binary-Eater/open-gpu-kernel-modules/commit/9af5a7d9313f49661c6918cd2954f618bf95dfd9) Patch file - https://github.com/Binary-Eater/open-gpu-kernel-modules/commit/9af5a7d9313f49661c6918cd2954f618bf95dfd9.patch Variant 2 - [Binary-Eater@14d93b5](https://github.com/Binary-Eater/open-gpu-kernel-modules/commit/14d93b52ce538ba0446508473482fc4da91be3a2) Patch file - https://github.com/Binary-Eater/open-gpu-kernel-modules/commit/14d93b52ce538ba0446508473482fc4da91be3a2.patch
> 
> Variant 1 is what we are hoping to ship in a future driver release, but variant 2 is provided in case there is some unique monitor issue with variant 1 for those that would like to test the fix ahead of time.
> 
> Thanks, Rahul Rameshbabu

Would you all mind to provide proper version of the packages you are using? This really would give clarity.

Here also for manual installation of Patch1/Patch2:


- Patch 1: `sudo pacman -U https://archive.cachyos.org/nvidia/patch-2-fix/nvidia-open-dkms-580.105.08-3.1-x86_64.pkg.tar.zst`
- Patch 2: `sudo pacman -U https://cdn77.cachyos.org/repo/x86_64_v3/cachyos-v3/nvidia-open-dkms-580.105.08-3-x86_64_v3.pkg.tar.zst`
- 
Utiliye dkms for faster testing :)

Edit: Updated Patch1/2

**Comment by AntonOellerer** [comment]
I'm currently using the `580.105.08-2` driver on arch, the resolution of my monitor is capped at `2048x1080@59.998` (from `2560x1440@60Hz`

[nvidia-bug-report.log.gz](https://github.com/user-attachments/files/23544804/nvidia-bug-report.log.gz)

**Comment by ptr1337** [comment]
> I'm currently using the `580.105.08-2` driver on arch, the resolution of my monitor is capped at `2048x1080@59.998` (from `2560x1440@60Hz`
> 
> [nvidia-bug-report.log.gz](https://github.com/user-attachments/files/23544804/nvidia-bug-report.log.gz)

Arch does not patch anything right now.

**Comment by lemminggw** [comment]
Would it be worth me trying patch 1? (@ptr1337 cachyos is on patch 2 if I am not mistaken so I know that one doesn't fix it for me) Sounded like from above that in my situation it would not have been fixed with either patch.

Also if it helps I could provide the copy of my edid. It is a custom one to add in a refresh rate that was not showing up properly.

**Comment by ptr1337** [comment]
> Would it be worth me trying patch 1? ([@ptr1337](https://github.com/ptr1337) cachyos is on patch 2 if I am not mistaken so I know that one doesn't fix it for me) Sounded like from above that in my situation it would not have been fixed with either patch.
> 
> Also if it helps I could provide the copy of my edid. It is a custom one to add in a refresh rate that was not showing up properly.

CachyOS is on Patch 2, I think due the second post with "preffered" there has been some confusion, you can see the used patch here:
https://github.com/CachyOS/kernel-patches/blob/master/6.17/misc/nvidia/0006-nvkms-Limit-default-maximum-TMDS-character-rate-to-3.patch

Please test both above posted one and report back, which one is working.

Edit: Modified Patch Number

**Comment by 1Naim** [comment]
> > Would it be worth me trying patch 1? ([@ptr1337](https://github.com/ptr1337) cachyos is on patch 2 if I am not mistaken so I know that one doesn't fix it for me) Sounded like from above that in my situation it would not have been fixed with either patch.
> > Also if it helps I could provide the copy of my edid. It is a custom one to add in a refresh rate that was not showing up properly.
> 
> CachyOS is on Patch 1, I think due the second post with "preffered" there has been some confusion, you can see the used patch here: https://github.com/CachyOS/kernel-patches/blob/master/6.17/misc/nvidia/0006-nvkms-Limit-default-maximum-TMDS-character-rate-to-3.patch
> 
> Please test both above posted one and report back, which one is working.

We're on patch 2.

@lemminggw what version of linux-cachyos-nvidia-open do you have? -4 didn't have the patch applied because... I forgot. -5 and kernels 6.17.8 should have it applied. Alternatively the dkms package in repos has it applied and you can also use the packages that Peter provided.

Thanks.

**Comment by lemminggw** [comment]
This is what I had installed when I did the dump before:

lib32-nvidia-utils 580.105.08-2
lib32-opencl-nvidia 580.105.08-2
linux-cachyos-lts-nvidia-open 6.12.56-3
linux-cachyos-nvidia-open 6.17.7-5
linux-firmware-nvidia 1:20251021-1
nvidia-utils 580.105.08-3
opencl-nvidia 580.105.08-3

Just tested patch 2 from above and no dice, trying patch 1 just to be sure and can attach another dump with that just for prosperity 👍

**Comment by lemminggw** [comment]
here is a dump from me trying patch 1 

[nvidia-bug-report.log.gz](https://github.com/user-attachments/files/23545299/nvidia-bug-report.log.gz)

let me know if any extra info I can provide could help.

**Comment by selkij** [comment]
I am forwarding this, as it happened with me using, **and** Arch Linux (lastest zen kernel with updated packages) **and** now Fedora 43. The option for 1920x1080@144 disappeared (both in x11 and wayland). Checking the logs, it were saying that the pixel clock was too high (365.1MHz). It also made performance an issue, with poor, unstable fps. I must precise I am on a laptop with a GTX 1650 Ti Mobile, and only started happening since I upgraded to 580.105.08-1. This is very frustrating.

**Comment by Daniel-V1** [comment]
Arch Linux, latest versions
local/nvidia-open 580.105.08-3
    NVIDIA open kernel modules
local/nvidia-settings 580.105.08-1
    Tool for configuring the NVIDIA graphics driver
local/nvidia-utils 580.105.08-2
    NVIDIA drivers utilities

Two monitors, one connected hdmi, one connect displayport. Both are the same model and should be running at 2560x1440 but are capped at 1920x1080 with the latest drivers - 

[nvidia-bug-report.log.gz](https://github.com/user-attachments/files/23554369/nvidia-bug-report.log.gz)

**Comment by PresiMarsopa** [comment]
Same problem with the screen resolution on Fedora 43

**Comment by es20490446e** [comment]
Patch 2 worked for me.

[nvidia-bug-report.log.gz](https://github.com/user-attachments/files/23556502/nvidia-bug-report.log.gz)

**Comment by abhilashdwarakanath-dot** [comment]
The latest linux-cachyos worked for me after a local compile. Thank you nvidia and CachyOS devs! Internal monitor is at 4K and the external is back to 1440p.

**Comment by shawqisherif** [comment]
@abhilashdwarakanath-dot is this a new update? which version ?

**Comment by abhilashdwarakanath-dot** [comment]
@shawqisherif I just downloaded the linux-cachyos tar from the repo. 6.17.8. It contains the latest nvidia patch. Compiled it locally and booted into it. Highest resolutions and refresh rates restored.

**Comment by shawqisherif** [comment]
@abhilashdwarakanath-dot you have cachyOS or arch installed, cause I have arch and I can't find the nvidia driver installed on my machine on cachyOS repo. maybe I should just wait the official update from arch.

**Comment by abhilashdwarakanath-dot** [comment]
Hi,

I have Manjaro KDE. I've learned the hard way that one should not run
frankendistros like manjaro base + cachyos repos.

I simply pull the kernel zip from cachyos' github, change options in the
pkgbuild, and compile/build, and install and regenerate my initram. That's
it.

-------------------------------------------------------------

Dr. rer. nat. Abhilash Dwarakanath
Deutsches Primatenzentrum
Göttingen

Disclaimer - No trees were harmed in the sending of this message. A large
number of electrons were however rather inconvenienced.

**Comment by DoomPenguin9** [comment]
I have the same issue with my second monitor, which is 2560x1080 and connected via HDMI, so not just an issue with DisplayPort.

**Comment by DakuFox** [comment]
Can confirm the latest driver also affects refresh rates. Installed the latest drivers(580.105.08), and my 1920x1080/100hz monitor could not exceed 60 Hz at all, even xrandr/kscreen doctor thought it was a 60hz monitor. Downgrading to the same drivers darklenre was on previously(580.95.05) 
is now allowing my monitor to run on 100hz without issue again.

Running a Fedora Kinoite 43 with KDE on RTX 2080 Super 8GB
Using the HDMI part for this monitor.

**Comment by Neh-EXE** [comment]
> Can confirm the latest driver also affects refresh rates. Installed the latest drivers(580.105.08), and my 1920x1080/100hz monitor could not exceed 60 Hz at all, even xrandr/kscreen doctor thought it was a 60hz monitor. Downgrading to the same drivers darklenre was on previously(580.95.05) is now allowing my monitor to run on 100hz without issue again.
> 
> Running a Fedora Kinoite 43 with KDE on RTX 2080 Super 8GB Using the HDMI part for this monitor.

Same here, 1920x1080/100hz monitor gets stuck on 60hz (Connected via HDMI,  EndeavourOS mercury neo with KDE on RTX 4060 8GB)

Downgrading to the 580.95.05 fixes it

**Comment by mkvlrn** [comment]
Problem has been acknowledged, and the workaround has been successful for pretty much anyone.

Maybe we could stop commenting _this very same information_ over and over again, as to not spam useless notifications to people subscribed to the issue awaiting a resolution?

**Comment by es20490446e** [comment]
Comment only if you are still experiencing the issue.

In that case provide both the method you used to test the patch, and the info generated when running on the terminal `nvidia-bug-report.sh`.

**Comment by ptr1337** [comment]
I have pushed now variant 2 for nvidia-open, nvidia-open-dkms and nvidia-open-lts also in the arch-testing repository.

**Comment by VirtualBoost** [comment]
So I just tried to update to variant 2 using the arch-testing repository because I have a similar issue to the one described in this thread. However, variant 2 did not fix my problem.

This is what I currently have in my system:

```
❯ sudo pacman -Qe | grep nvidia
lib32-nvidia-utils 580.105.08-2
lib32-opencl-nvidia 580.105.08-2
libva-nvidia-driver 0.0.14-1.1
nvidia-open-dkms 580.105.08-3
nvidia-settings 580.95.05-2
nvidia-utils 580.105.08-3
opencl-nvidia 580.105.08-3
```

The issue I have is that when I turn on my monitor (Alienware AW3225QF), I have the correct settings, which is 3840x2160 at 240hz. However, as soon as the monitor goes into sleep and then wakes up by me moving the mouse, etc., it will default to 3840x2160 at 60hz. If I try to change the refresh rate, I can only find the 60hz options or below that, 240hz is not present. I have to restart the system in order to make the 240hz option to return. Can this be fixed somehow as it is very annoying, especially with an OLED monitor?

[nvidia-bug-report.log.gz](https://github.com/user-attachments/files/23572025/nvidia-bug-report.log.gz)

**Comment by Binary-Eater** [comment]
@VirtualBoost, we are aware that variant 2 does not fix some monitors. That is not the final solution we will choose for fixing this issue on a future driver release. Thank you for sharing the nvidia-bug-report.log.gz. The more of those we have especially for people not seeing the issue resolved with variant 2, is helpful

**Comment by VirtualBoost** [comment]
> @VirtualBoost, we are aware that variant 2 does not fix some monitors. That is not the final solution we will choose for fixing this issue on a future driver release. Thank you for sharing the nvidia-bug-report.log.gz. The more of those we have especially for people not seeing the issue resolved with variant 2, is helpful

That is great to hear, thanks. Not related to this topic, but is the flickering desktop in KDE scheduled to be fixed in the near future (don't want to derail the question but figured I could ask when I have the chance)? I am referring to this issue: 

https://forums.developer.nvidia.com/t/nvidia-555-58-4k-120hz-causes-flickering-artifacting-on-x-and-wayland-with-arch/298187/49

**Comment by Binary-Eater** [comment]
Hi @VirtualBoost,

Thanks for bringing this up. In general, I have been noticing a number of VRR related issues so I have been looking at them as a whole.
However, I am not familiar with that specific thread. I suspect an internal bug was not opened yet since Amrit could not get an internal reproduction for me or another engineer to look at. I will sync up with him on this thread during the work week.

Do not hesitate to mention me directly in the forums `@rrameshbabu`.

**Comment by AntonOellerer** [comment]
580.105.08-2 on arch fixed it for me fyi (Monitor LG 27UN880)

**Comment by veypatch** [comment]
> Sadly my LG ULTRAWIDE connected over HDMI (should be 2560x1080@75Hz) is still capped at 1920x1080@60Hz. My second displayport monitor won't output any thing at all (connected through a thinkpad dock).

I can confirm with the latest cachyos version (variant 2) this has been fixed for me. Sorry for the earlier misinformation about variant 2 already being in the build.

**Comment by VirtualBoost** [comment]
Wanted to add that as long that I have my second monitor (connected with Displayport, a Dell U2724D) turned on, the issue stops to happen for me, even if my main monitor (AW3225QF, connected with HDMI) goes to sleep/turns off.

**Comment by djkunkel** [comment]
I'm on Bazzite with 580.105.08. I have not applied any patches, but my secondary monitor is stuck at 60Hz on this release. Thought I'd send my nvidia-bug-report.log.gz.

[nvidia-bug-report.log.gz](https://github.com/user-attachments/files/23596278/nvidia-bug-report.log.gz)

**Comment by avDuma** [comment]
Same behaviour here:

- Kernel version: Linux 6.17.8-arch1-1
- Windowing system: X11
- OS: Arch Linux 64-bit
- Graphic card: NVIDIA GeForce GTX 1050 Ti
- Monitor: LG29UM58-P

After upgrading to **580.105.08-3** resolution of monitor shrinked to 1920x1080/60 Hz .
Previously was 2560x1080

**Comment by Bobrokus** [comment]
> Comment only if you are still experiencing the issue.
> 
> In that case provide both the method you used to test the patch, and the info generated when running on the terminal `nvidia-bug-report.sh`.

You mean with or without the patch?

**Comment by dbalaazs** [comment]
The issue also happened with the proprietary drivers on fedora. I have a 2560x1080 secondary monitor @ 75Hz plugged into HDMI on a gtx 1660s and version 580.105.08 limited my resolution to 1920x1080@60 and stretched the image. Downgrading to 580.95.05 fixed the issue.

**Comment by CarolCarrot3520** [comment]
> The issue also happened with the proprietary drivers on fedora. I have a 2560x1080 secondary monitor @ 75Hz plugged into HDMI on a gtx 1660s and version 580.105.08 limited my resolution to 1920x1080@60 and stretched the image. Downgrading to 580.95.05 fixed the issue.

How did you downgrade to 580.95.05 on Fedora, since i swear its only 570 that you can downgrade to in the repos. But it could just be me being sleep deprived.

**Comment by MKlown** [comment]
Hello, when can we expect a patch that is diffused through official repos?

**Comment by dbalaazs** [comment]
> > The issue also happened with the proprietary drivers on fedora. I have a 2560x1080 secondary monitor @ 75Hz plugged into HDMI on a gtx 1660s and version 580.105.08 limited my resolution to 1920x1080@60 and stretched the image. Downgrading to 580.95.05 fixed the issue.
> 
> How did you downgrade to 580.95.05 on Fedora, since i swear its only 570 that you can downgrade to in the repos. But it could just be me being sleep deprived.

I downgraded to 580.95.05 with dnf, then removed the pre compiled kmod package, cleared the build cache and triggered a clean compile with akmods. it was a doozy to figure out as a novice

**Comment by CarolCarrot3520** [comment]
Oh, 580.95.05 is in the updates repo again.

**Comment by Bobrokus** [comment]
> Oh, 580.95.05 is in the updates repo again.

In Fedora's? Fedora 42 or 43? I don't see it in 42's. What's the name of the package?

**Comment by dbalaazs** [comment]
> > Oh, 580.95.05 is in the updates repo again.
> 
> In Fedora's? Fedora 42 or 43? I don't see it in 42's. What's the name of the package?

On fedora 43. I versionlocked the old driver packages until a patch gets released. Heres the list


Package name: akmod-nvidia
evr = 3:580.95.05-1.fc43


Package name: xorg-x11-drv-nvidia
evr = 3:580.95.05-1.fc43


Package name: xorg-x11-drv-nvidia-libs
evr = 3:580.95.05-1.fc43


Package name: nvidia-modprobe
evr = 3:580.95.05-1.fc43


Package name: nvidia-settings
evr = 3:580.95.05-1.fc43


Package name: nvidia-persistenced
evr = 3:580.95.05-1.fc43


Package name: nvidia-libXNVCtrl
evr = 3:580.95.05-1.fc42

**Comment by Binary-Eater** [comment]
Just for everyone's reference, this is the patch we plan to roll out in future driver releases.

* https://github.com/Binary-Eater/open-gpu-kernel-modules/commit/331496883e2823184b92de1983f254f93577acc0
* https://github.com/Binary-Eater/open-gpu-kernel-modules/commit/331496883e2823184b92de1983f254f93577acc0.patch

**Comment by Bobrokus** [comment]
Found the previous Fedora 42 package [akmod-nvidia-580.95.05-1.fc42.x86_64](https://rpmfind.net/linux/rpmfusion/nonfree/fedora/updates/42/x86_64/a/akmod-nvidia-580.95.05-1.fc42.x86_64.rpm) @ https://rpmfind.net

Edit:
The downgrade worked 🥳 My refresh rate now works as before!
What I did:
```sh
# remove all nvidia related packages
sudo dnf remove *nvidia*
# make sure system is up to date before installing the downgrade
sudo dnf update -y
# install the downgraded package
sudo dnf install https://rpmfind.net/linux/rpmfusion/nonfree/fedora/updates/42/x86_64/a/akmod-nvidia-580.95.05-1.fc42.x86_64.rpm \
# for some reason it wants to install an old cuda-libs package instead of 580xx - exclude them
--exclude=xorg-x11-drv-nvidia-390xx-cuda-libs,xorg-x11-drv-nvidia-470xx-cuda-libs,xorg-x11-drv-nvidia-390xx-cuda-libs \
# use --repofrompath to let it pull the correct versions of the dependecies from the source repo
--repofrompath=repofind,https://rpmfind.net/linux/rpmfusion/nonfree/fedora/updates/42/x86_64 \
# and disable rpmfusion, because we want to pull from the repo above
--disablerepo="rpmfusion*"
```

**Comment by ptr1337** [comment]
> Just for everyone's reference, this is the patch we plan to roll out in future driver releases.
> 
> * [Binary-Eater@3314968](https://github.com/Binary-Eater/open-gpu-kernel-modules/commit/331496883e2823184b92de1983f254f93577acc0)
> * https://github.com/Binary-Eater/open-gpu-kernel-modules/commit/331496883e2823184b92de1983f254f93577acc0.patch

Thanks for writing. I will push it into the archlinux and cachyos repository.

**Comment by Binary-Eater** [comment]
Thanks @ptr1337 for the help!

**Comment by ptr1337** [comment]
Fix has been now deployed in the arch testing repository. Will move in a few hours into the stable repository.

The patch is **only applied to the nvidia-open-dkms, nvidia-open and nvidia-open-lts packages***

**Comment by VirtualBoost** [comment]
Unfortunately, the patch does not fix the issue for me after monitor goes to sleep and then wakes back up again. I can see on the monitor information that displays whenever it gets a signal that it says "2160p 32bit" when it bugs out. When it doesn't bug out, like when the PC just has started, it will say something like "3840x2160,30bit,240hz" instead.

I will attach a new bug report file so you can have a look. Hopefully it can be fixed.

[nvidia-bug-report.log.gz](https://github.com/user-attachments/files/23696013/nvidia-bug-report.log.gz)

**Comment by Binary-Eater** [comment]
> Unfortunately, the patch does not fix the issue for me after monitor goes to sleep and then wakes back up again. I can see on the monitor information that displays whenever it gets a signal that it says "2160p 32bit" when it bugs out. When it doesn't bug out, like when the PC just has started, it will say something like "3840x2160,30bit,240hz" instead.
> 
> I will attach a new bug report file so you can have a look. Hopefully it can be fixed.
> 
> [nvidia-bug-report.log.gz](https://github.com/user-attachments/files/23696013/nvidia-bug-report.log.gz)

Anything related to sleep and wake up of a monitor is likely a separate issue. I think you already made a separate issue for this on the forums? We can triage this issue separately.

**Comment by kode54** [comment]
I have two monitors, one Asus XG27UCS and one LG 24UD58-B. Prior to the latest patch, the secondary monitor, when connected over DP, would fail to wake from DPMS sleep. Now with this patch, it wakes from DPMS.

However, on DP and not HDMI, that secondary monitor has periodic flickering while nothing is on the desktop except the wallpaper.

KDE / Kwin 6.5.3 Wayland session, Arch Linux. I'll try to post a log and report on the forums.

**Comment by VirtualBoost** [comment]
> > Unfortunately, the patch does not fix the issue for me after monitor goes to sleep and then wakes back up again. I can see on the monitor information that displays whenever it gets a signal that it says "2160p 32bit" when it bugs out. When it doesn't bug out, like when the PC just has started, it will say something like "3840x2160,30bit,240hz" instead.
> > I will attach a new bug report file so you can have a look. Hopefully it can be fixed.
> > [nvidia-bug-report.log.gz](https://github.com/user-attachments/files/23696013/nvidia-bug-report.log.gz)
> 
> Anything related to sleep and wake up of a monitor is likely a separate issue. I think you already made a separate issue for this on the forums? We can triage this issue separately.

I agree with you, @Binary-Eater. I have created a separate post in the Nvidia Forum and attached two bug reports: one before the bug occurs and one after the bug has occured.

https://forums.developer.nvidia.com/t/monitor-refresh-rate-bugs-out-after-going-to-sleep/352353

**Comment by feng-yifan** [comment]
The problem still same, my monitor's max resolution is still 1920x1080@60. I have two same monitors, that connected with DP working well
```
Output "PNP(AOC) Q27P1B GNXJ7HA960050" (DP-2)
  Current mode: 2560x1440 @ 59.951 Hz (preferred)
  Variable refresh rate: not supported
  Physical size: 600x340 mm
  Logical position: 2560, -350
  Logical size: 1440x2560
  Scale: 1
  Transform: 270° counter-clockwise
  Available modes:
    2560x1440@59.951 (current, preferred)
    1920x1080@60.000
    1920x1080@59.939
    1920x1080@50.000
    1280x1440@59.913
    1680x1050@59.954
    1280x1024@75.025
    1280x1024@60.020
    1440x900@59.887
    1280x960@60.000
    1280x720@60.000
    1280x720@59.943
    1280x720@50.000
    1024x768@75.029
    1024x768@70.069
    1024x768@60.004
    800x600@75.000
    800x600@72.188
    800x600@60.317
    800x600@56.250
    720x576@50.000
    720x480@59.940
    640x480@75.000
    640x480@72.809
    640x480@59.940
    640x480@59.929

Output "PNP(AOC) Q27P1B GNXJ8HA017977" (HDMI-A-1)
  Current mode: 1920x1080 @ 60.000 Hz
  Variable refresh rate: not supported
  Physical size: 600x340 mm
  Logical position: -1440, -350
  Logical size: 1080x1920
  Scale: 1
  Transform: 90° counter-clockwise
  Available modes:
    1920x1080@60.000 (current)
    1920x1080@59.939
    1920x1080@50.000
    1280x1440@59.913
    1680x1050@59.954
    1280x1024@75.025
    1280x1024@60.020
    1440x900@59.887
    1280x960@60.000
    1280x720@60.000
    1280x720@59.943
    1280x720@50.000
    1024x768@75.029
    1024x768@70.069
    1024x768@60.004
    800x600@75.000
    800x600@72.188
    800x600@60.317
    800x600@56.250
    720x576@50.000
    720x480@59.940
    640x480@75.000
    640x480@72.809
    640x480@59.940
    640x480@59.929
```

**Comment by lemminggw** [comment]
I was able to confirm with latest nvidia in cachy os my issue is resolved with the custom edid I was running and all resolutions/refresh rate combos I should have are available. So seems like the latest patch version worked for me.

for ref versions of nvidia stuff installed:
lib32-nvidia-utils 580.105.08-2
lib32-opencl-nvidia 580.105.08-2
libva-nvidia-driver 0.0.14-1.1
linux-cachyos-lts-nvidia-open 6.12.59-2
linux-cachyos-nvidia-open 6.17.9-2
linux-firmware-nvidia 1:20251111-1
nvidia-settings 580.105.08-2
nvidia-utils 580.105.08-4
opencl-nvidia 580.105.08-4

**Comment by lordsaveth** [comment]
I let go of IgnorePkg and tried to see if the issue is fixed for me on latest 580.105.08-2 version, nvidia-open-dkms, Arch Linux (not testing)

Resolution issue is unfortunately still happening for me (monitor with native 1440p only goes up to 2560x1080).

EDIT: bug report I attached could be not so useful.

**Comment by Binary-Eater** [comment]
> I let go of IgnorePkg and tried to see if the issue is fixed for me on latest 580.105.08-2 version, nvidia-open-dkms, Arch Linux (not testing)
> 
> Resolution issue is unfortunately still happening for me (monitor with native 1440p only goes up to 2560x1080).
> 
> [nvidia-bug-report.log.gz](https://github.com/user-attachments/files/23738695/nvidia-bug-report.log.gz)

580.105.08-2 is not the latest?

 - https://archlinux.org/packages/extra/x86_64/nvidia-open/
- https://archlinux.org/packages/extra/x86_64/nvidia-open-dkms/

**Comment by lordsaveth** [comment]
> > I let go of IgnorePkg and tried to see if the issue is fixed for me on latest 580.105.08-2 version, nvidia-open-dkms, Arch Linux (not testing)
> > Resolution issue is unfortunately still happening for me (monitor with native 1440p only goes up to 2560x1080).
> > [nvidia-bug-report.log.gz](https://github.com/user-attachments/files/23738695/nvidia-bug-report.log.gz)
> 
> 580.105.08-2 is not the latest?
> 
>     * https://archlinux.org/packages/extra/x86_64/nvidia-open/
> 
>     * https://archlinux.org/packages/extra/x86_64/nvidia-open-dkms/

My apologies, it was late and I probably wrote down the wrong version. Whatever the latest version in Arch Linux extra repo was last night, was the version I tried, as I simply unignored the related packages and allowed them to update as normal (assuming maybe it was 580.105.08-4).

Anyways, I wouldn't just be commenting that, I went ahead and tried again to update to latest (which is weird because it should be the same versions of the same packages), and this time, _**native 1440p over hdmi works for me on 580.105.08-4 nvidia-open-dkms.**_ No idea why it wasn't working last night,  but now it is 🥳 . (btw should go without saying, but i'll say anyways that post-install both times I restarted to ensure I got the new kernel/modules)...

thanks to the maintainers for the support~!

**Comment by feng-yifan** [comment]
@lordsaveth have you installed lib32-nvidia-utils? I update nvidia-dkms and nvidia-utils to latest version, HDMI resolution is still 1080p.

**Comment by lordsaveth** [comment]
@feng-yifan yes, i have lib32-nvidia-utils, and i allowed all nvidia packages to update to latest (vanilla arch). as stated i did have to upgrade and downgrade multiple times, seemingly to the same version, for the fix to actually work. so i'm not sure if there is additional intervention steps that could fix your situation

edit: has the fix been applied to the proprietary "nvidia-dkms" too? @feng-yifan are you using that or the open kernel module (of this repo)

**Comment by shawqisherif** [comment]
is there any news, when is this issue going to be solved, we have like  three minor updates now ( fixes )

**Comment by fhilipecrash** [comment]
> [@lordsaveth](https://github.com/lordsaveth) have you installed lib32-nvidia-utils? I update nvidia-dkms and nvidia-utils to latest version, HDMI resolution is still 1080p.

As mentioned above, only the -open versions of the drivers have the patch. I use nvidia-open and everything is working as it should again.
> The patch is only applied to the nvidia-open-dkms, nvidia-open and nvidia-open-lts packages*

**Comment by feng-yifan** [comment]
> [@feng-yifan](https://github.com/feng-yifan) yes, i have lib32-nvidia-utils, and i allowed all nvidia packages to update to latest (vanilla arch). as stated i did have to upgrade and downgrade multiple times, seemingly to the same version, for the fix to actually work. so i'm not sure if there is additional intervention steps that could fix your situation
> 
> edit: has the fix been applied to the proprietary "nvidia-dkms" too? [@feng-yifan](https://github.com/feng-yifan) are you using that or the open kernel module (of this repo)

Shit, I didn't notice this is the open kernel module, this is my bad! Thank you for notice me

**Comment by janmaroto** [comment]
I also experienced this on my laptop, since this update. I have it in the IgnorePKG for now.
Did this get solved with the latest 580.105.08-4 (Arch Linux) package?

These are my specs, in case it helps.
Model: MSI GS65 Stealth Thin 8RF REV:1.0 
GPU: NVIDIA GeForce GTX 1070 Mobile (Max-Q)
Display: Dell S2716DG
OS: Arch Linux
Kernel: 6.17.9-arch1-1
DE: KDE Plasma 6.5.3 
WM: kwin
Optimus is enabled in Hybrid mode.

**Comment by kozlek** [comment]
Issue is fixed for me with `nvidia-open 580.105.08-6` (RTX 3080, monitor connected to card DisplayPort using an HDMI to DisplayPort cable).
Thanks for your help !

**Comment by abhilashdwarakanath-dot** [comment]
Hi,

Uhhh. So connecting the external monitor via a USB-C dock (where the HDMI
cable gets plugged into the dock) is regressing its resolution and refresh
rate. Plugging it in directly to the laptop's HDMI restores 2560x1440.
Strange.

**Comment by MeghBadonia** [comment]
> ### NVIDIA Open GPU Kernel Modules Version
> 580.105.08
> 
> ### Please confirm this issue does not happen with the proprietary driver (of the same version). This issue tracker is only for bugs specific to the open kernel driver.
> * [ ]  I confirm that this does not happen with the proprietary driver package.
> 
> ### Operating System and Version
> CachyOS
> 
> ### Kernel Release
> 6.17.7-3-cachyos
> 
> ### Please confirm you are running a stable release kernel (e.g. not a -rc). We do not accept bug reports for unreleased kernels.
> * [x]  I am running on a stable kernel release.
> 
> ### Hardware: GPU
> NVIDIA RTX A2000 12GB
> 
> ### Describe the bug
> ## Bug Report
> **NVIDIA Driver Version:** 580.105.08 **Previous Working Version:** 580.95.05 **GPU:** NVIDIA RTX A2000 12GB **OS:** CachyOS (Arch-based) **Kernel:** 6.17.7 **Display Server:** Wayland (KDE Plasma 6.5.1) **Monitor:** Lenovo ThinkVision T27h-30 (2560x1440 native) **Connection:** Mini-DisplayPort to DisplayPort
> 
> ## Issue
> After updating from driver 580.95.05 to 580.105.08, my DisplayPort-connected monitor is limited to 1920x1080 maximum resolution instead of its native 2560x1440@60Hz.
> 
> ## Evidence
> * EDID correctly reports 2560x1440 as preferred mode
> * `/sys/class/drm/card1-DP-1/modes` shows maximum 1920x1080
> * `edid-decode` confirms monitor advertises 2560x1440@60Hz
> * Downgrading to 580.95.05 resolves the issue
> 
> ## Reproduction
> 1. Update nvidia-utils to 580.105.08
> 2. Connect 2560x1440 DisplayPort monitor
> 3. Check available resolutions - maximum is 1920x1080
> 
> ## Related Reports
> Multiple users affected: https://discuss.cachyos.org/t/after-updating-linux-cachyos-nvidia-linux-cachyos-rc-nvidia-linux-cachyos-lts-nvidia-nvidia-driver-version-580-105-08-the-dual-screen-display-resolution-is-incorrect/18057
> 
> https://discuss.cachyos.org/t/suddenly-missing-higher-resolution-on-second-monitor/18101/14
> 
> ### To Reproduce
> 1. Update nvidia-utils to 580.105.08
> 2. Connect 2560x1440 DisplayPort monitor
> 3. Check available resolutions - maximum is 1920x1080
> 
> ### Bug Incidence
> Always
> 
> ### nvidia-bug-report.log.gz
> [nvidia-bug-report.log.gz](https://github.com/user-attachments/files/23383730/nvidia-bug-report.log.gz)
> 
> ### More Info
> _No response_

Same with me with HDMI limited with 1080p @ 60fps

**Comment by SupImCinnamon** [comment]
Not sure if this is related, but my main monitor gets stuck to 640x480@60Hz after waking from sleep, it is supposed to go up to 1920x1080@144Hz, and it does fine at boot. Using nvidia-open-dkms 580.105.08-4 from vanilla arch.

edid ->
```
00 ff ff ff ff ff ff 00 3a c4 00 00 00 00 00 00
00 00 01 04 95 00 00 78 ee 91 a3 54 4c 99 26 0f
50 54 00 20 00 00 01 01 01 01 01 01 01 01 01 01
01 01 01 01 01 01 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 92
```

xrandr ->
```
DP-2 connected 640x480+1920+0 (normal left inverted right x axis y axis) 595mm x 336mm
   640x480       59.38*+
   320x240       59.29  
   640x400       59.20  
   320x200       58.14  
   640x350       59.28 
```

[nvidia-bug-report.log.gz](https://github.com/user-attachments/files/23872584/nvidia-bug-report.log.gz)

**Comment by rsysadmin-com** [comment]
openSUSE Tumbleweed user here with pretty much the same packages installed.

In my case, the `nvidia.persistenced` service failed to start, despite all permissions for the user and group were correct on the `/dev/nvidia*` files.

There's no SELinux installed and AppArmor isn't prohibiting anything for this.

**Comment by Dreyyyyy** [comment]
Same problem with RTX 3050 on EndeavourOS, just downgrading to 580.95.05 worked.

**Comment by fiauxthales** [comment]
Same with me. GTX 1060 on fedora 42 and fedora 43.

**Comment by ang-63** [comment]
I’d like to add another data point to this regression on 580.105.08.

**GPU:** RTX 4070 Ti SUPER  
**Monitor:** AOC AGON PRO AG326UD (32" 3840×2160 165 Hz OLED, DisplayPort)  
**Connection:** DisplayPort  
**Driver:** 580.105.08 (both proprietary and open-kernel variants, depending on distro)  
**Previous versions tested:** I have not yet tried downgrading to 580.95.05, but multiple users report that 580.95.05 does not have this issue.

**Distros / compositors tested (all Wayland):**

- Fedora 43 GNOME
- Nobara 43 GNOME
- CachyOS GNOME
- CachyOS + Arch “bare” Hyprland
- Fedora 43 niri (Wayland compositor: https://github.com/YaLTeR/niri/issues/2989)

In all of these environments:

- The compositor *reports* that 3840×2160@165 Hz is active,
- but the monitor’s OSD “Information” page always shows a horizontal frequency of **~388 kHz**, which corresponds to **120 Hz**, not 165 Hz.
- I never see the 520–535 kHz range that would match 165 Hz on this OLED on 580.105.08.

So effectively, the driver silently falls back to 120 Hz while still telling the compositor that 165 Hz is applied.

### Behaviour per compositor

- **GNOME 49 (Wayland):** Display settings allow selecting 165 Hz; UI says 165 Hz is active; OSD shows Adaptive-Sync at ~120 Hz.
- **Hyprland (wlroots):** `hyprctl monitors` shows 3840x2160@165, but OSD again reports ~120 Hz.
- **niri 25.11:** When I set 165/160/144 Hz in niri’s config on 580.105.08, the OLED output either goes black or niri falls back to 60/120 Hz. OSD never shows 165 Hz being actually used.

This is reproducible across:

- Fedora/Nobara (RPM-based, NVIDIA “open kernel” configured via `MODULE_VARIANT=kernel-open`)
- CachyOS/Arch (with `nvidia-open-dkms` installed)

On these systems, the kernel ends up loading `nvidia.ko` instead of `nvidia-open.ko`, but the refresh-rate behaviour is the same: 580.105.08 never truly drives this monitor above 120 Hz on Wayland.

### Why this looks like the same regression

Just like in this issue, upgrading to 580.105.08:

- breaks previously working high-resolution/high-refresh modes on DisplayPort,
- behaves the same across multiple compositors and distros,
- and looks like a DRM/KMS-level regression rather than a compositor bug.

My detailed compositor-side report is here (for niri):  
https://github.com/YaLTeR/niri/issues/2989

If it’s helpful, I can attach:

- `drm_info` outputs from “good” vs “bad” setups,
- EDID dumps,
- and logs from different compositors.

Right now the main thing I can confirm is:  
**with 580.105.08 the monitor never actually receives 165 Hz over DP on Linux Wayland, even though all compositors believe that mode is active.**

**Comment by Binary-Eater** [comment]
This should be fixed with driver 580.119.02. For any other issues, please open a separate bug.

**Comment by Binary-Eater** [comment]
@ang-63 that sounds like a separate issue with DP link assessment FWIW.
