### ISSUE TITLE
580.119.02 causing display to blink constantly on debian

### ISSUE THREAD

**Issue by rchris494** [NVIDIA/open-gpu-kernel-modules#986]
### NVIDIA Open GPU Kernel Modules Version

580.119.02

### Please confirm this issue does not happen with the proprietary driver (of the same version). This issue tracker is only for bugs specific to the open kernel driver.

- [x] I confirm that this does not happen with the proprietary driver package.

### Operating System and Version

debian 14

### Kernel Release

kernel 6.12.58

### Please confirm you are running a stable release kernel (e.g. not a -rc). We do not accept bug reports for unreleased kernels.

- [x] I am running on a stable kernel release.

### Hardware: GPU

nvidia 3070 and nvidia 4080 super

### Describe the bug

so who the hell did you have QC nvidia 580.119.02 driver? stevie wonder or ray charles? it is constantly blinking the display on all 3 of my debian systems one with a 3060. 3070. and a 4080 super.

### To Reproduce

just install it in debian and use a display port. then watch it constantly blink in full screen with just SSH open. open anything else and it is far worse.

### Bug Incidence

Once

### nvidia-bug-report.log.gz

just install the thing. if you can't figure out that it is constantly with apps in full screen blinking you need glasses

**Comment by RevenantX** [comment]
Confirm on XFWM4 with compositing enabled - LXQt panel is blinking, QTerminal also blinking. With disabled compositing all works better. This also happens on closed driver. Reverting to 580.105.08 fixes problem

**Comment by Binary-Eater** [comment]
Hi, I apologize about this regression. I am currently not in front of a development machine to try to repro this myself to debug, but will try to take a look at this as soon as I have access to a development setup.

**Comment by fanboimsft** [comment]
same issue on 590.48.01and 590.44.01 XFWM4 with composting enabled, 4070ti
no issue on 580.105.08

**Comment by abchauhan-nv** [comment]
Thank you for reporting the issue. Can you please capture a NVIDIA bug report from the system after you run into this issue and attach it here. We are checking if we can reproduce this on our systems.

**Comment by abchauhan-nv** [comment]
Hi all, Tracking this on an internal bug - 5758240. We can reproduce this issue on our systems. This is under investigation. Thank you

**Comment by abchauhan-nv** [comment]
Unfortunately, the only work around to avoid this issue on 580.119.02 is to disable compositing under Settings -> Window Manager Tweaks -> Compositor -> Enable display compositing. We are actively working on fixing this issue.

**Comment by Binary-Eater** [comment]
To add to @abchauhan-nv comment, if you would like compositing in the meantime, you can use an external compositing client like compton till we have this issue resolved.

https://www.neowin.net/forum/topic/1148464-using-compton-for-tear-free-compositing-in-xfce/

**Comment by cr4i50n** [comment]
> Unfortunately, the only work around to avoid this issue on 580.119.02 is to disable compositing under Settings -> Window Manager Tweaks -> Compositor -> Enable display compositing. We are actively working on fixing this issue.

picom (compton ?) compositing is broken on ArchLinux as well on 590.48.0 https://github.com/yshui/picom/issues/1488
problems with flickering (repaint) in GTK3 applications and in Electron38 (vscode renders weird cursor misalignments on menu elements - after several passes over it with the cursor it highlights wrong elements).

reverting to 580.95.05 completely solves this flickering with picom compositing.

( insane quality control at nvidia! )

**Comment by joostoudeman** [comment]
what baffles me is that if I open NVIDIA Settings, the problem doesn't occur.

**Comment by yshui** [comment]
> @Binary-Eater To add to [@abchauhan-nv](https://github.com/abchauhan-nv) comment, if you would like compositing in the meantime, you can use an external compositing client like compton till we have this issue resolved.
> 
> https://www.neowin.net/forum/topic/1148464-using-compton-for-tear-free-compositing-in-xfce/

what a blast from the past :D

that's a 12 years old thread you are referencing, and compton has been dead for 8 years now... 

and no, an external compositor is not going to help either, like people have said. picom is experiencing the same problem as well.

**Comment by Binary-Eater** [comment]
@yshui thanks for calling this out. The last time I used an external compositor application was around 12-13 years ago. Also, I do recognize this situation is less than ideal. With regards to the current situation with `picom`, we identified the regressor area internally and would expect the main area of impact to be the X render protocol. I presume `picom` is similar to the original `compton` and has multiple backends. Are you seeing the same regression with the `glx` backend as well?

**Comment by Binary-Eater** [comment]
Just took a look at https://github.com/yshui/picom/issues/1488. That's interesting.

**Comment by cr4i50n** [comment]
> [@yshui](https://github.com/yshui) thanks for calling this out. The last time I used an external compositor application was around 12-13 years ago. Also, I do recognize this situation is less than ideal. With regards to the current situation with `picom`, we identified the regressor area internally and would expect the main area of impact to be the X render protocol. I presume `picom` is similar to the original `compton` and has multiple backends. Are you seeing the same regression with the `glx` backend as well?

we're talking glx here. picom is used almost exclusively in glx these days.

just checked picom's xrender backend and the performance is somewhat bad, with lag in focusing windows under the cursor (in awesomewm) (Edit: after enabling use-ewmh-active-win = true; no more focus lag), but the flicker is gone and menus don't do misaligned cursor nor highlight wrong submenus after scrolling through them in Electron (vscode).

```
❯ nvidia-smi
Fri Dec 26 14:08:28 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 590.48.01              Driver Version: 590.48.01      CUDA Version: 13.1     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3080        On  |   00000000:07:00.0  On |                  N/A |
|  0%   42C    P8             14W /  295W |     665MiB /  10240MiB |      7%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            1329      G   /usr/lib/Xorg                           386MiB |
|    0   N/A  N/A            1695    C+G   ...rack-uuid=3190708988185955192        133MiB |
|    0   N/A  N/A            4802      G   alacritty                                10MiB |
|    0   N/A  N/A            4977      G   /usr/lib/electron39/electron             70MiB |
|    0   N/A  N/A            5620      G   alacritty                                10MiB |
+-----------------------------------------------------------------------------------------+
```

**Comment by xBZZZZ** [comment]
>* [x] I confirm that this does not happen with the proprietary driver package.

I don't think picom bug ([github link](https://github.com/yshui/picom/issues/1488), [nvidia link](https://forums.developer.nvidia.com/t/picom-sometimes-doesnt-repaint-gtk-3-with-nvidia-driver-590-44-01/355216)) is same as this

for me picom bug happens with these nvidia kernel drivers (proprietary userspace libraries with same version):
* 590.44.01 proprietary
* 590.44.01 open source
* 590.48.01 proprietary
* 590.48.01 open source

for me picom bug doesn't happen with these nvidia kernel drivers (proprietary userspace libraries with same version):
* 580.105.08 open source

others untested

**Comment by Binary-Eater** [comment]
@xBZZZZ if you are willing, would you mind testing `picom` with 580.119.02? That's the driver version with the regression in the 580 driver branch. 580.105.08 is known to work fine for both issues. If not, I will give this a try myself.

**Comment by xBZZZZ** [comment]
> [@xBZZZZ](https://github.com/xBZZZZ) if you are willing, would you mind testing `picom` with 580.119.02?

I can't find 580.119.02 rpm packages in https://developer.download.nvidia.com/compute/cuda/repos/opensuse15/x86_64/

**Comment by BarbUk** [comment]
> @xBZZZZ if you are willing, would you mind testing picom with 580.119.02? That's the driver version with the regression in the 580 driver branch. 580.105.08 is known to work fine for both issues. If not, I will give this a try myself.

I can confirm that the issue exists with `580.119.02`.

```
❯ nvidia-smi
Tue Dec 30 10:05:30 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.119.02             Driver Version: 580.119.02     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060 Ti     Off |   00000000:01:00.0  On |                  N/A |
| 53%   47C    P8             15W /  200W |     240MiB /   8192MiB |      6%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
```

EDIT: And the issue is gone with `580.105.08`.

```
❯ nvidia-smi
Tue Dec 30 10:15:31 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.105.08             Driver Version: 580.105.08     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060 Ti     Off |   00000000:01:00.0  On |                  N/A |
|  0%   48C    P8             14W /  200W |     676MiB /   8192MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
```

**Comment by abchauhan-nv** [comment]
Thank you for the details.  We can reproduce the issues with picom on our systems. This is likely to have the same root cause as 5758240.

**Comment by BarbUk** [comment]
Thanks @abchauhan-nv.

If it can help, my [picom configuration is here](https://github.com/BarbUk/dotfiles/blob/739eacbb4e2235f5a7e62d6e662293c0a130aee1/apps/picom.conf).

Following the nvidia driver update on the 590.X branch, i tried to mitigate the issue by disabling `damage` and `unredir-if-possible` ([commit](https://github.com/BarbUk/dotfiles/commit/821cae8f4b96cd165cb3640acc293a6acc069e42)),  this was better, but still visible.

Happy to help more if you need.

**Comment by Mikael-Lovqvist** [comment]
> that's a 12 years old thread you are referencing, and compton has been dead for 8 years now...
> 
> and no, an external compositor is not going to help either, like people have said. picom is experiencing the same problem as well.

I don't know if it helps nailing down the problem, but, I dug up and compiled it, and the flicker was gone! Other than not being actively maintained, `compton` seem to be a better fit for my needs than `picom`, it usually *just works* while I keep having issues with `picom` (though I might have a weird system/config/brain or something).

**Comment by yshui** [comment]
@Mikael-Lovqvist `compton` defaults to xrender which i think is unaffected. you can get the same thing on `picom` with `--backend xrender`.

**Comment by jeremywh7** [comment]
> Confirm on XFWM4 with compositing enabled - LXQt panel is blinking, QTerminal also blinking. With disabled compositing all works better. This also happens on closed driver. Reverting to 580.105.08 fixes problem

Same issue running Arch with LXQt on both xfwm4 (X) and labwc (Wayland); fixed since updating to -testing repos a few days ago:
```
Name            : nvidia-open-dkms
Name            : nvidia-utils
Version         : 590.48.01-2
```

**Comment by xBZZZZ** [comment]
>fixed since updating to -testing repos a few days ago

what was the bad nvidia driver version before update?

**Comment by jeremywh7** [comment]
> what was the bad nvidia driver version before update?

```
[2026-01-08T19:21:10-0500] [ALPM] upgraded nvidia-utils (590.48.01-1.1 -> 590.48.01-2)
[2026-01-08T19:21:13-0500] [ALPM] upgraded nvidia-open-dkms (590.48.01-1.1 -> 590.48.01-2)
```
Ah, they had to rebuild for python 3.14:

> [upgpkg: 590.48.01-2: python 3.14 rebuild](https://gitlab.archlinux.org/archlinux/packaging/packages/nvidia-utils/-/commit/f653d806)
> [Frederik Schwan](https://gitlab.archlinux.org/freswa) authored 1 week ago

I just rebuilt pkgbuilder for that actually.  ;-)

**Comment by xBZZZZ** [comment]
with nvidia driver `590.48.01-2` (the after update one), do gtk 3 tabs get stuck with `picom --backend=egl --no-use-damage` or `picom --backend=glx --no-use-damage` like in video in https://forums.developer.nvidia.com/t/picom-sometimes-doesnt-repaint-gtk-3-with-nvidia-driver-590-44-01/355216?

**Comment by jeremywh7** [comment]
>do gtk 3 tabs get stuck with picom

I haven't used picom in years, since I switched from openbox to xfwm4 which has a built-in compositor.

**Comment by abchauhan-nv** [comment]
Hi all, we’ve completed the investigation and identified the root cause. The fix will be available in upcoming drivers. Thanks.

**Comment by rchris494** [comment]
580.126.18 same thing. maybe by 2027 it might have a fix

**Comment by xBZZZZ** [comment]
> 580.126.18 same thing. maybe by 2027 it might have a fix

<a href="https://www.nvidia.com/en-us/drivers/details/265309/">595.45.04</a> also exists but <b>not</b> in <a href="https://developer.download.nvidia.com/compute/cuda/repos/opensuse15/x86_64/">opensuse repository</a>

**Comment by BarbUk** [comment]
> [595.45.04](https://www.nvidia.com/en-us/drivers/details/265309/) also exists but not in [opensuse repository](https://developer.download.nvidia.com/compute/cuda/repos/opensuse15/x86_64/)

The release is 2 hours old, 
https://github.com/NVIDIA/open-gpu-kernel-modules/releases/tag/595.45.04, it will be packaged soon

**Comment by BarbUk** [comment]
I did not realize 595.45.04 was a beta release.
It's not packaged as stable on many os.

I just installed the release, and the issue from this thread is fixed:
```
❯ nvidia-smi
Tue Mar 10 01:09:19 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 595.45.04              Driver Version: 595.45.04      CUDA Version: 13.2     |
+-----------------------------------------+------------------------+----------------------+
```

**Comment by PassiveLemon** [comment]
I can also confirm that 595.45.05 fixes the gtk flickering

**Comment by metzm** [comment]
Wow, this bug has been backported to the 580 line of drivers with at least 580.126.20 released on Feb 23 2026. At this time, this bug was (should have been) well known.

**Comment by pogman-code** [comment]
> Wow, this bug has been backported to the 580 line of drivers with at least 580.126.20 released on Feb 23 2026. At this time, this bug was (should have been) well known.

I *think* it has been fixed in 580.142, I installed it recently and it seems fine so far.

Maybe in few days I will take it back though, to be continued...

**Comment by abchauhan-nv** [comment]
Hi all,

Yes, the fix is now available in [580.142](https://www.nvidia.com/en-us/drivers/details/265587/).

The release highlights include the following note about this regression:
“Fixed a regression introduced in the 580.119.02 driver release which caused some X11 compositors (e.g. picom, Xfwm) to blink.”

Please let us know if it continues to reproduce on your systems. Thank you for your patience.

**Comment by rchris494** [comment]
yeah. 580.142 seems to have cleaned up all of the problems with the blinking of everything. i have been test driving it for a little while now. i don't have any of the previous problems that i had with the other drivers.

**Comment by glektarssza** [comment]
For anyone else still having this issue after the driver update and is using xfce4 (and thus `xfwm4`); the solution for me was to also do the following:

1.Generate a fresh X11 config:
```sh
nvidia-xconfig --prime -o ~/xorg.test.conf
```
2. Check the config for issues (naturally).
3. Move the config to the `/etc/X11` directory.
4. Put the following in `~/.xinitrc`:
```sh
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto
```
5. Set `xfwm4`'s vblank mode (this is the one that finally fully resolved it for me) either via the settings editor application or the following command:
```sh
xfconf-query --channel xfwm4 --create --type string --property /general/vblank_mode --set xpresent
```

Step 5, as mentioned, is what fully solved it for me. I've listed all the steps I tried, in sequence, though, in case any were part of the overall full solution.

Hopefully this helps anyone who was still struggling with this like I was!

**Comment by mhalano** [comment]
Nice! I got some artifacts on my screen with the Obsidian app under 4K, but it was GNOME Shell on Wayland. I will update, and I hope now it's fixed.
